name: 🚀 Deploy Website to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 📦 Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, curl, json
          coverage: none

      - name: 📦 Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - name: 🚀 Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp

          server-dir: ./

          state-name: .ftp-deploy-sync-state.json
          dangerous-clean-slate: false

          exclude: |
            **/.git*
            **/.github/**
            **/.vscode/**
            **/adminlte-template/**
            **/node_modules/**
            **/tests/**
            **/.env
            **/phpunit.xml
            **/.editorconfig
            **/.gitattributes
            **/README.md
